version: '3'

services:
  zookeeper:
    environment:
        ZOOKEEPER_CLIENT_PORT: '2181'
    image: 'confluentinc/cp-zookeeper:7.5.3'
    ports:
        - '2181:2181'

  kafka:
    container_name: kafka
    environment:
        KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
        KAFKA_LISTENERS: 'PLAINTEXT://:29092,PLAINTEXT_HOST://:9092'
        KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092'
        KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
        KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
        KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
        KAFKA_BROKER_ID: 1
        KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    image: 'confluentinc/cp-kafka:7.5.3'
    ports:
        - '9092:9092'
    depends_on:
        - zookeeper
    command: sh -c "((sleep 15 && kafka-topics --create --zookeeper zookeeper:2181 --replication-factor 1 --partitions 1 --topic "consumer.test-topic")&) && /etc/confluent/docker/run "

volumes:
  database-data:
    driver: local
